ui_print "-----------------------"
ui_print "          __   __    __"
ui_print "  ___ _  / /  / /   / /"
ui_print " / _ `/ / /  / _ \ / / "
ui_print " \_, / /_/  /_.__//_/  "
ui_print "/___/                  "
ui_print "-----------------------"
ui_print ""
ui_print "Changed Android model to GM1917"
