ui_print "-----------------------"
ui_print "          __   __    __"
ui_print "  ___ _  / /  / /   / /"
ui_print " / _ \`/ / /  / _ \ / / "
ui_print " \_, / /_/  /_.__//_/  "
ui_print "/___/  FPS Unlocker    "
ui_print "-----------------------"
ui_print ""
ui_print "---------------------------------"
ui_print "Successfully changed device model"
ui_print "          Happy gaming!          "
ui_print "---------------------------------"
